language: java
jdk: oraclejdk8

sudo: required

before_install:
  - chmod +x mvnw

# Code coverage
after_success:
  - mvn clean test jacoco:report coveralls:report

# cache between builds
cache:
  directories:
  - $HOME/.m2